import { IMdxDoc } from '../../types';

export const articles: IMdxDoc[] = [
  {
    meta: {
      slug: 'the-real-reason-you-need-an-icp',
      date: '2021-09-01',
      title: 'The Real Reason You Need an ICP',
      subtitle: `You've heard the term, but here's the real reason that not having one is holding you back.`,
      coverImage: '/articles/cover-images/the-real-reason-you-need-an-icp.webp',
      authorName: 'Dave Benjamin',
      authorAvatar: '/dave.png',
      tags: ['ICP', 'Product Strategy', 'User Experience'],
      categories: ['Product', 'UX'],
      keywords: [
        'ICP',
        'Ideal Customer Profile',
        'Product Strategy',
        'User Experience',
      ],
      abstract: [
        'The term ICP is thrown around a lot, but what does it really mean?',
        'Here’s the real reason you need an ICP and how to get one.',
        'You might be surprised at how bad the advice you have been getting is.',
      ],
      published: true,
    },
  },
  {
    meta: {
      slug: 'understanding-digital-experience',
      date: '2021-10-15',
      title: 'Understanding Digital Experience',
      subtitle: 'How Digital Experience Drives Customer Engagement',
      coverImage: '/articles/cover-images/understanding-digital-experience.webp',
      authorName: 'Jane Smith',
      authorAvatar: '/jane.png',
      tags: ['Digital Experience', 'Customer Engagement', 'DX'],
      categories: ['Digital', 'CX'],
      keywords: ['Digital Experience', 'Customer Engagement', 'DX'],
      abstract: [
        'Digital experience is a crucial aspect of modern customer engagement.',
        'Learn how to optimize digital touchpoints to enhance user satisfaction.',
        'Discover tools and strategies to improve your digital experience.',
      ],
      published: true,
    },
  },
  {
    meta: {
      slug: 'improving-customer-journeys',
      date: '2021-11-10',
      title: 'Improving Customer Journeys',
      subtitle: 'Mapping and Optimizing Customer Touchpoints',
      coverImage: '/articles/cover-images/improving-customer-journeys.webp',
      authorName: 'Alice Johnson',
      authorAvatar: '/alice.png',
      tags: ['Customer Journeys', 'Touchpoints', 'CX'],
      categories: ['Customer Experience', 'CX'],
      keywords: ['Customer Journeys', 'Touchpoints', 'Customer Experience'],
      abstract: [
        'Understand the importance of mapping customer journeys.',
        'Learn techniques to optimize each touchpoint for better CX.',
        'Improve your overall customer satisfaction by refining journeys.',
      ],
      published: true,
    },
  },
  {
    meta: {
      slug: 'the-future-of-ux-design',
      date: '2022-01-05',
      title: 'The Future of UX Design',
      subtitle: 'Trends and Predictions for the Next Decade',
      coverImage: '/articles/cover-images/the-future-of-ux-design.webp',
      authorName: 'Michael Lee',
      authorAvatar: '/michael.png',
      tags: ['UX Design', 'Future Trends', 'User Experience'],
      categories: ['Design', 'UX'],
      keywords: ['UX Design', 'Future Trends', 'User Experience'],
      abstract: [
        'Explore the future trends in UX design.',
        'Understand how new technologies will shape user experiences.',
        'Prepare your design strategy for the next decade.',
      ],
      published: true,
    },
  },
  {
    meta: {
      slug: 'designing-for-empathy',
      date: '2022-02-20',
      title: 'Designing for Empathy',
      subtitle: 'Creating User-Centric Experiences',
      coverImage: '/articles/cover-images/designing-for-empathy.webp',
      authorName: 'Emily Davis',
      authorAvatar: '/emily.png',
      tags: ['Empathy', 'User-Centric Design', 'UX'],
      categories: ['Design', 'UX'],
      keywords: ['Empathy', 'User-Centric Design', 'UX'],
      abstract: [
        'Learn how to design with empathy to create user-centric experiences.',
        'Discover techniques to understand and address user needs.',
        'Enhance user satisfaction by integrating empathy in design.',
      ],
      published: true,
    },
  },
  {
    meta: {
      slug: 'measuring-ux-success',
      date: '2022-03-15',
      title: 'Measuring UX Success',
      subtitle: 'Key Metrics and Tools',
      coverImage: '/articles/cover-images/measuring-ux-success.webp',
      authorName: 'Robert Brown',
      authorAvatar: '/robert.png',
      tags: ['UX Metrics', 'Success Measurement', 'User Experience'],
      categories: ['Analytics', 'UX'],
      keywords: ['UX Metrics', 'Success Measurement', 'User Experience'],
      abstract: [
        'Identify the key metrics to measure UX success.',
        'Explore tools that help you track and analyze UX performance.',
        'Improve your design based on data-driven insights.',
      ],
      published: true,
    },
  },
  {
    meta: {
      slug: 'enhancing-developer-experience',
      date: '2022-04-10',
      title: 'Enhancing Developer Experience',
      subtitle: 'Best Practices for DX',
      coverImage: '/articles/cover-images/enhancing-developer-experience.webp',
      authorName: 'Sarah Green',
      authorAvatar: '/sarah.png',
      tags: ['Developer Experience', 'DX', 'Best Practices'],
      categories: ['Development', 'DX'],
      keywords: ['Developer Experience', 'DX', 'Best Practices'],
      abstract: [
        'Learn how to enhance developer experience for better productivity.',
        'Explore best practices and tools for improving DX.',
        'Understand the impact of DX on overall software quality.',
      ],
      published: true,
    },
  },
  {
    meta: {
      slug: 'personalizing-customer-experience',
      date: '2022-05-05',
      title: 'Personalizing Customer Experience',
      subtitle: 'Techniques for Effective Personalization',
      coverImage: '/articles/cover-images/personalizing-customer-experience.webp',
      authorName: 'Tom White',
      authorAvatar: '/tom.png',
      tags: ['Personalization', 'Customer Experience', 'CX'],
      categories: ['Marketing', 'CX'],
      keywords: ['Personalization', 'Customer Experience', 'CX'],
      abstract: [
        'Discover techniques to personalize customer experiences.',
        'Learn how to use data to drive effective personalization.',
        'Enhance customer satisfaction with tailored experiences.',
      ],
      published: true,
    },
  },
];
